start transaction;
insert into movies (id, title, year) values (1, 'Silent Scream, The', 1998);
insert into movies (id, title, year) values (2, 'Den tatuerade änkan (Tattooed Widow, The) ', 1992);
insert into movies (id, title, year) values (3, 'Alien Predator (Mutant II) (Falling, The)', 2006);
insert into movies (id, title, year) values (4, 'Demonic', 2006);
insert into movies (id, title, year) values (5, 'Last Ride, The', 2001);
insert into movies (id, title, year) values (6, 'Jean-Michel Basquiat: The Radiant Child', 2001);
insert into movies (id, title, year) values (7, 'Autumn Heart, The', 2009);
insert into movies (id, title, year) values (8, 'The Count of Monte Cristo', 2010);
insert into movies (id, title, year) values (9, 'Tinseltown', 2001);
insert into movies (id, title, year) values (10, 'Multiplicity', 1985);
insert into movies (id, title, year) values (11, 'Being Elmo: A Puppeteer''s Journey', 2012);
insert into movies (id, title, year) values (12, 'Tangerines', 1993);
insert into movies (id, title, year) values (13, 'Ghosts of Mississippi', 1999);
insert into movies (id, title, year) values (14, 'The Mascot', 1985);
insert into movies (id, title, year) values (15, 'Dalton, Les', 1985);
insert into movies (id, title, year) values (16, 'Ichi', 1992);
insert into movies (id, title, year) values (17, 'Guardian Angel', 2004);
insert into movies (id, title, year) values (18, 'Taxi Driver', 1992);
insert into movies (id, title, year) values (19, 'Louise-Michel', 1986);
insert into movies (id, title, year) values (20, 'Gods of the Plague (Götter der Pest)', 2001);
insert into movies (id, title, year) values (21, 'Thrill Ride: The Science of Fun', 2009);
insert into movies (id, title, year) values (22, 'Moebius', 2001);
insert into movies (id, title, year) values (23, 'Memento', 1991);
insert into movies (id, title, year) values (24, 'Centenarian Who Climbed Out the Window and Vanished, The (Hundraåringen som klev ut genom fönstret och försvann)', 1990);
insert into movies (id, title, year) values (25, 'Everyone''s Hero', 2012);
insert into movies (id, title, year) values (26, 'Descent, The', 2008);
insert into movies (id, title, year) values (27, 'Ghostmaker, The (Box of Shadows)', 2012);
insert into movies (id, title, year) values (28, 'Wanderlust', 2008);
insert into movies (id, title, year) values (29, 'Everyones Hero', 2003);
insert into movies (id, title, year) values (30, 'Hatari!', 2009);
insert into movies (id, title, year) values (31, 'Don''t Look Now: We''re Being Shot At (La grande vadrouille)', 1993);
insert into movies (id, title, year) values (32, 'Shanghai Dreams (Qing hong)', 2002);
insert into movies (id, title, year) values (33, 'Tuvalu', 2002);
insert into movies (id, title, year) values (34, 'Shaft''s Big Score!', 2011);
insert into movies (id, title, year) values (35, 'Salvatore Giuliano', 2001);
insert into movies (id, title, year) values (36, 'Crisis', 1999);
insert into movies (id, title, year) values (37, 'Repulsion', 2010);
insert into movies (id, title, year) values (38, 'Demon Wind', 2012);
insert into movies (id, title, year) values (39, 'Anastasia', 2011);
insert into movies (id, title, year) values (40, 'Sullivan''s Travels', 1993);
insert into movies (id, title, year) values (41, 'SpongeBob SquarePants Movie, The', 2012);
insert into movies (id, title, year) values (42, 'Digging Up the Marrow', 1995);
insert into movies (id, title, year) values (43, 'Gia', 1998);
insert into movies (id, title, year) values (44, 'In Two Minds', 1990);
insert into movies (id, title, year) values (45, 'Winter Light (Nattvardsgästerna)', 2010);
insert into movies (id, title, year) values (46, 'In a Glass Cage (Tras el cristal)', 2009);
insert into movies (id, title, year) values (47, 'Red Heat', 2007);
insert into movies (id, title, year) values (48, 'Girl with a Pearl Earring', 2008);
insert into movies (id, title, year) values (49, 'Elling', 2008);
insert into movies (id, title, year) values (50, 'Harvey', 2004);
insert into movies (id, title, year) values (51, 'Crow: City of Angels, The', 2002);
insert into movies (id, title, year) values (52, 'Virginia City', 2011);
insert into movies (id, title, year) values (53, 'Billy Madison', 1988);
insert into movies (id, title, year) values (54, 'Little Italy', 2008);
insert into movies (id, title, year) values (55, 'Volunteers', 1985);
insert into movies (id, title, year) values (56, 'Nuremberg', 2004);
insert into movies (id, title, year) values (57, 'Selena', 1997);
insert into movies (id, title, year) values (58, 'Baboona', 2006);
insert into movies (id, title, year) values (59, 'Red Hill', 2007);
insert into movies (id, title, year) values (60, 'Newlyweds', 1998);
insert into movies (id, title, year) values (61, 'Cathy Come Home', 2012);
insert into movies (id, title, year) values (62, 'Björk: Volumen', 2005);
insert into movies (id, title, year) values (63, 'Brenda Starr', 2011);
insert into movies (id, title, year) values (64, 'Raspberry Boat Refugee', 1996);
insert into movies (id, title, year) values (65, 'Beyond Borders', 1982);
insert into movies (id, title, year) values (66, 'Nowhere', 2008);
insert into movies (id, title, year) values (67, 'Evangelion: 3.0 You Can (Not) Redo', 1995);
insert into movies (id, title, year) values (68, 'Evidence ', 2012);
insert into movies (id, title, year) values (69, 'Ragnarok', 2010);
insert into movies (id, title, year) values (70, 'Jean de Florette', 2006);
insert into movies (id, title, year) values (71, 'Glorious Technicolor', 1999);
insert into movies (id, title, year) values (72, 'Alligator Eyes', 2010);
insert into movies (id, title, year) values (73, 'Curiosity of Chance, The', 2007);
insert into movies (id, title, year) values (74, 'On Dangerous Ground', 1994);
insert into movies (id, title, year) values (75, 'Strongest Man in the World, The', 2007);
insert into movies (id, title, year) values (76, 'Ferngully: The Last Rainforest', 2006);
insert into movies (id, title, year) values (77, 'Civic Duty', 2004);
insert into movies (id, title, year) values (78, 'Yonkers Joe', 2011);
insert into movies (id, title, year) values (79, 'Half a Loaf of Kung Fu (Dian zhi gong fu gan chian chan)', 1975);
insert into movies (id, title, year) values (80, 'Exit', 2008);
insert into movies (id, title, year) values (81, 'Invisible Woman, The', 1985);
insert into movies (id, title, year) values (82, 'Blackout', 2012);
insert into movies (id, title, year) values (83, 'Once Upon a Time in China (Wong Fei Hung)', 2008);
insert into movies (id, title, year) values (84, 'Greening of Whitney Brown, The', 2007);
insert into movies (id, title, year) values (85, 'Operation Homecoming: Writing the Wartime Experience', 2009);
insert into movies (id, title, year) values (86, 'In the Mood For Love (Fa yeung nin wa)', 1986);
insert into movies (id, title, year) values (87, 'Lured', 1996);
insert into movies (id, title, year) values (88, 'People in Places', 2008);
insert into movies (id, title, year) values (89, 'My Super Ex-Girlfriend', 2001);
insert into movies (id, title, year) values (90, 'Easy Living', 1991);
insert into movies (id, title, year) values (91, 'Autobiography of Nicolae Ceausescu, The (Autobiografia lui Nicolae Ceausescu)', 1990);
insert into movies (id, title, year) values (92, 'Danny Deckchair', 1994);
insert into movies (id, title, year) values (93, 'Grande école', 1998);
insert into movies (id, title, year) values (94, '6 Days to Air: The Making of South Park', 2009);
insert into movies (id, title, year) values (95, '21 tapaa pilata avioliitto', 2003);
insert into movies (id, title, year) values (96, 'Artemisia', 2008);
insert into movies (id, title, year) values (97, 'Swingers', 1994);
insert into movies (id, title, year) values (98, 'Dust in the Wind (Lian lian feng chen)', 2012);
insert into movies (id, title, year) values (99, 'All Mine to Give', 1991);
insert into movies (id, title, year) values (100, 'Night the Lights Went Out in Georgia, The', 2013);
commit;