insert into release_dates (movie_id, country, release_date, note) values (1, 'Indonesia', 1997, 'Self-enabling');
insert into release_dates (movie_id, country, release_date, note) values (2, 'China', 1984, 'toolset');
insert into release_dates (movie_id, country, release_date, note) values (3, 'China', 2010, 'content-based');
insert into release_dates (movie_id, country, release_date, note) values (4, 'United States', 2010, 'didactic');
insert into release_dates (movie_id, country, release_date, note) values (5, 'Indonesia', 1994, 'middleware');
insert into release_dates (movie_id, country, release_date, note) values (6, 'Sweden', 2006, 'Synchronised');
insert into release_dates (movie_id, country, release_date, note) values (7, 'Poland', 2011, 'well-modulated');
insert into release_dates (movie_id, country, release_date, note) values (8, 'Serbia', 1995, 'systematic');
insert into release_dates (movie_id, country, release_date, note) values (9, 'Philippines', 1996, 'Distributed');
insert into release_dates (movie_id, country, release_date, note) values (10, 'Russia', 1961, 'matrices');
insert into release_dates (movie_id, country, release_date, note) values (11, 'Papua New Guinea', 2005, 'multimedia');
insert into release_dates (movie_id, country, release_date, note) values (12, 'China', 2006, 'open architecture');
insert into release_dates (movie_id, country, release_date, note) values (13, 'China', 2001, 'moderator');
insert into release_dates (movie_id, country, release_date, note) values (14, 'Greece', 1985, 'groupware');
insert into release_dates (movie_id, country, release_date, note) values (15, 'China', 1996, 'hybrid');
insert into release_dates (movie_id, country, release_date, note) values (16, 'Brazil', 2012, 'directional');
insert into release_dates (movie_id, country, release_date, note) values (17, 'Poland', 2012, '3rd generation');
insert into release_dates (movie_id, country, release_date, note) values (18, 'Djibouti', 1997, 'Balanced');
insert into release_dates (movie_id, country, release_date, note) values (19, 'China', 1991, 'Optional');
insert into release_dates (movie_id, country, release_date, note) values (20, 'Greece', 2011, 'web-enabled');
insert into release_dates (movie_id, country, release_date, note) values (21, 'China', 2001, 'Face to face');
insert into release_dates (movie_id, country, release_date, note) values (22, 'Tunisia', 2001, 'Secured');
insert into release_dates (movie_id, country, release_date, note) values (23, 'China', 2009, 'Inverse');
insert into release_dates (movie_id, country, release_date, note) values (24, 'Slovenia', 1995, 'radical');
insert into release_dates (movie_id, country, release_date, note) values (25, 'Macedonia', 2009, 'complexity');
insert into release_dates (movie_id, country, release_date, note) values (26, 'Indonesia', 1992, 'application');
insert into release_dates (movie_id, country, release_date, note) values (27, 'South Africa', 2003, 'Focused');
insert into release_dates (movie_id, country, release_date, note) values (28, 'Malta', 1994, 'core');
insert into release_dates (movie_id, country, release_date, note) values (29, 'Comoros', 1997, 'zero defect');
insert into release_dates (movie_id, country, release_date, note) values (30, 'Ukraine', 2007, 'Seamless');
insert into release_dates (movie_id, country, release_date, note) values (31, 'Montenegro', 2004, 'Synchronised');
insert into release_dates (movie_id, country, release_date, note) values (32, 'Brazil', 1995, 'bottom-line');
insert into release_dates (movie_id, country, release_date, note) values (33, 'China', 2012, 'disintermediate');
insert into release_dates (movie_id, country, release_date, note) values (34, 'South Africa', 1991, 'De-engineered');
insert into release_dates (movie_id, country, release_date, note) values (35, 'South Korea', 2003, 'local');
insert into release_dates (movie_id, country, release_date, note) values (36, 'China', 1996, 'Realigned');
insert into release_dates (movie_id, country, release_date, note) values (37, 'Portugal', 1999, 'Re-engineered');
insert into release_dates (movie_id, country, release_date, note) values (38, 'United States', 2005, 'Multi-tiered');
insert into release_dates (movie_id, country, release_date, note) values (39, 'Japan', 2000, 'Profound');
insert into release_dates (movie_id, country, release_date, note) values (40, 'Albania', 2004, 'Extended');
insert into release_dates (movie_id, country, release_date, note) values (41, 'Japan', 2009, 'tangible');
insert into release_dates (movie_id, country, release_date, note) values (42, 'Lithuania', 1992, 'asymmetric');
insert into release_dates (movie_id, country, release_date, note) values (43, 'Thailand', 2010, 'adapter');
insert into release_dates (movie_id, country, release_date, note) values (44, 'Venezuela', 1992, 'Switchable');
insert into release_dates (movie_id, country, release_date, note) values (45, 'Martinique', 2012, 'even-keeled');
insert into release_dates (movie_id, country, release_date, note) values (46, 'Russia', 2008, '6th generation');
insert into release_dates (movie_id, country, release_date, note) values (47, 'China', 2008, 'attitude-oriented');
insert into release_dates (movie_id, country, release_date, note) values (48, 'Canada', 2009, 'ability');
insert into release_dates (movie_id, country, release_date, note) values (49, 'China', 2005, 'initiative');
insert into release_dates (movie_id, country, release_date, note) values (50, 'Russia', 1963, 'Graphical User Interface');
insert into release_dates (movie_id, country, release_date, note) values (51, 'Sweden', 1995, 'Monitored');
insert into release_dates (movie_id, country, release_date, note) values (52, 'Poland', 2003, 'orchestration');
insert into release_dates (movie_id, country, release_date, note) values (53, 'Czech Republic', 2006, 'groupware');
insert into release_dates (movie_id, country, release_date, note) values (54, 'China', 2008, '24 hour');
insert into release_dates (movie_id, country, release_date, note) values (55, 'Thailand', 1991, 'alliance');
insert into release_dates (movie_id, country, release_date, note) values (56, 'Sierra Leone', 2012, 'explicit');
insert into release_dates (movie_id, country, release_date, note) values (57, 'Indonesia', 1992, 'demand-driven');
insert into release_dates (movie_id, country, release_date, note) values (58, 'Russia', 2009, 'adapter');
insert into release_dates (movie_id, country, release_date, note) values (59, 'Brazil', 2009, 'multi-tasking');
insert into release_dates (movie_id, country, release_date, note) values (60, 'Indonesia', 2001, 'success');
insert into release_dates (movie_id, country, release_date, note) values (61, 'Gabon', 1995, 'throughput');
insert into release_dates (movie_id, country, release_date, note) values (62, 'Albania', 1987, 'neural-net');
insert into release_dates (movie_id, country, release_date, note) values (63, 'Sweden', 1998, 'Persevering');
insert into release_dates (movie_id, country, release_date, note) values (64, 'Poland', 1998, 'success');
insert into release_dates (movie_id, country, release_date, note) values (65, 'Russia', 1989, 'superstructure');
insert into release_dates (movie_id, country, release_date, note) values (66, 'Thailand', 2009, 'web-enabled');
insert into release_dates (movie_id, country, release_date, note) values (67, 'Russia', 1999, 'Distributed');
insert into release_dates (movie_id, country, release_date, note) values (68, 'China', 1997, 'static');
insert into release_dates (movie_id, country, release_date, note) values (69, 'China', 1994, 'asymmetric');
insert into release_dates (movie_id, country, release_date, note) values (70, 'Portugal', 2001, 'Centralized');
insert into release_dates (movie_id, country, release_date, note) values (71, 'China', 2003, 'standardization');
insert into release_dates (movie_id, country, release_date, note) values (72, 'China', 2009, 'orchestration');
insert into release_dates (movie_id, country, release_date, note) values (73, 'Philippines', 2007, 'policy');
insert into release_dates (movie_id, country, release_date, note) values (74, 'Sweden', 2005, 'executive');
insert into release_dates (movie_id, country, release_date, note) values (75, 'China', 2004, 'Vision-oriented');
insert into release_dates (movie_id, country, release_date, note) values (76, 'Poland', 1997, 'Enhanced');
insert into release_dates (movie_id, country, release_date, note) values (77, 'Thailand', 1989, 'standardization');
insert into release_dates (movie_id, country, release_date, note) values (78, 'South Africa', 2011, 'capacity');
insert into release_dates (movie_id, country, release_date, note) values (79, 'Peru', 2001, 'clear-thinking');
insert into release_dates (movie_id, country, release_date, note) values (80, 'Palestinian Territory', 2005, 'Secured');
insert into release_dates (movie_id, country, release_date, note) values (81, 'China', 1997, 'Universal');
insert into release_dates (movie_id, country, release_date, note) values (82, 'Philippines', 2006, 'Total');
insert into release_dates (movie_id, country, release_date, note) values (83, 'Sudan', 2006, 'bi-directional');
insert into release_dates (movie_id, country, release_date, note) values (84, 'Bulgaria', 2007, 'Networked');
insert into release_dates (movie_id, country, release_date, note) values (85, 'Slovenia', 1996, 'Team-oriented');
insert into release_dates (movie_id, country, release_date, note) values (86, 'Argentina', 2013, 'radical');
insert into release_dates (movie_id, country, release_date, note) values (87, 'China', 2008, 'homogeneous');
insert into release_dates (movie_id, country, release_date, note) values (88, 'Indonesia', 2004, 'collaboration');
insert into release_dates (movie_id, country, release_date, note) values (89, 'Russia', 2008, 'intermediate');
insert into release_dates (movie_id, country, release_date, note) values (90, 'Indonesia', 1997, 'Secured');
insert into release_dates (movie_id, country, release_date, note) values (91, 'Albania', 2007, 'demand-driven');
insert into release_dates (movie_id, country, release_date, note) values (92, 'Mongolia', 2007, 'grid-enabled');
insert into release_dates (movie_id, country, release_date, note) values (93, 'Costa Rica', 1991, 'Polarised');
insert into release_dates (movie_id, country, release_date, note) values (94, 'Guatemala', 2000, 'Distributed');
insert into release_dates (movie_id, country, release_date, note) values (95, 'Ukraine', 2005, 'Total');
insert into release_dates (movie_id, country, release_date, note) values (96, 'Indonesia', 2013, 'synergy');
insert into release_dates (movie_id, country, release_date, note) values (97, 'China', 2004, 'Business-focused');
insert into release_dates (movie_id, country, release_date, note) values (98, 'Indonesia', 1992, '4th generation');
insert into release_dates (movie_id, country, release_date, note) values (99, 'Ethiopia', 2007, 'product');
insert into release_dates (movie_id, country, release_date, note) values (100, 'United States', 2002, 'user-facing');
